---
- name: Install required packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop: "{{ package_list }}"
  when: package_list is defined

- name: Add Docker's official GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
    state: present
- name: Update apt package index
  ansible.builtin.apt:
    update_cache: yes
- name: Install Docker Engine
  ansible.builtin.apt:
    name: docker-ce
    state: present
- name: Install Docker client
  ansible.builtin.apt:
    name: docker-ce-cli
    state: present
- name: Ensure Docker service is running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
