---
- name: Install MySQL server
  ansible.builtin.apt:
    name: mysql-server
    state: present

- name: Ensure MySQL service is running
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: true
- name: Install PyMySQL Python library (required for Ansible MySQL modules)
  ansible.builtin.apt:
    name: python3-pymysql
    state: present
  become: true

- name: Create application database
  community.mysql.mysql_db:
    name: "{{ app_db_name }}"
    state: present
    login_user: root
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create application user
  community.mysql.mysql_user:
    name: "{{ app_db_user }}"
    password: "{{ app_db_password }}"
    priv: "{{ app_db_name }}.*:ALL"
    state: present
    login_user: root
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Remove anonymous users
  community.mysql.mysql_user:
    name: ''
    host_all: true
    state: absent
    login_user: root
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Remove test database
  community.mysql.mysql_db:
    name: test
    state: absent
    login_user: root
    login_unix_socket: /var/run/mysqld/mysqld.sock
